# Generated by Django 5.2.17 on 2026-08-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_groups'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='controlnumbersequence',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', True)), fields=('prefix',), name='unique_prefix_when_year_null'),
        ),
    ]
