# Generated by Django 5.2.17 on 2026-08-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_grant_group_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, help_text="SHA-256 of the uploaded file's bytes. IMPORTANT 7: the simplest reliable way to notice a re-upload of the same file -- the filename alone changes too easily to trust.", max_length=64),
        ),
    ]
