# Generated by Django 5.2.17 on 2026-08-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importbatch_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedperson',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, help_text='Stable identity of this response in its source, used to skip rows already staged. For a Google Forms export it is the submission timestamp, which never changes as the sheet grows.', max_length=64),
        ),
    ]
