# Generated by Django 5.2.17 on 2026-08-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_committeemembership_historicalcommitteemembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemembership',
            name='role',
            field=models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('CO_CHAIR', 'Co-Chair'), ('SECRETARY', 'Secretary'), ('MEMBER', 'Member'), ('OVERSIGHT', 'Board Oversight'), ('EX_OFFICIO', 'Member by office')], default='MEMBER', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalcommitteemembership',
            name='role',
            field=models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('CO_CHAIR', 'Co-Chair'), ('SECRETARY', 'Secretary'), ('MEMBER', 'Member'), ('OVERSIGHT', 'Board Oversight'), ('EX_OFFICIO', 'Member by office')], default='MEMBER', max_length=12),
        ),
    ]
