# Generated by Django 5.2.17 on 2026-08-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_secretary_and_ex_officio_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-start_date',), 'verbose_name': 'church position', 'verbose_name_plural': 'church positions'},
        ),
        migrations.AlterModelOptions(
            name='historicalappointment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical church position', 'verbose_name_plural': 'historical church positions'},
        ),
    ]
