# Generated by Django 5.2.17 on 2026-08-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_rename_appointment_to_church_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='has_officers',
            field=models.BooleanField(default=True, help_text="Whether this committee has a chairperson, co-chair and secretary of its own. False for an appointed body whose members are named by the Board rather than led from within — Grievance and Reconciliation, whose members include the church's pastors. An empty officer post is not a vacancy for such a committee, so the overview stops reporting it as one."),
        ),
    ]
