# Generated by Django 5.2.17 on 2026-08-16 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='For example, "Malong Family".', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HEAD', 'Head'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('OTHER', 'Other')], max_length=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='people.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='people.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('household', 'person'), name='unique_person_per_household')],
            },
        ),
    ]
