# Generated by Django 5.2.17 on 2026-08-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_household_householdmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='public_greeting_consent',
            field=models.BooleanField(default=False, help_text="The member has agreed their name may be posted on the church's public Facebook page for birthdays and wedding anniversaries."),
        ),
        migrations.AddField(
            model_name='person',
            name='public_greeting_consent',
            field=models.BooleanField(default=False, help_text="The member has agreed their name may be posted on the church's public Facebook page for birthdays and wedding anniversaries."),
        ),
    ]
