# Generated by Django 5.2.17 on 2026-08-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_household_householdmember'),
        ('records', '0002_alter_accesslog_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_label', models.CharField(max_length=220)),
                ('fields_cleared', models.TextField()),
                ('history_rows_scrubbed', models.IntegerField(default=0)),
                ('purged_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person')),
            ],
            options={
                'ordering': ('-purged_at',),
            },
        ),
    ]
