# Generated by Django 5.2.17 on 2026-08-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_purgerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='purgerecord',
            name='scan_files_removed',
            field=models.IntegerField(default=0, help_text='Number of FormScan images deleted from storage for this person. The FormScan rows themselves are kept -- only the photograph is removed -- so this count is the audit evidence that the scans were dealt with, not just the database fields.'),
        ),
    ]
